### ISSUE TITLE
Get URL metadata

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-backend#124]
The current source manager automatically retrieves metadata from an URI when the URI matches a GitLab URL. However, this only works for GitLab projects (obviously).
Create a function that checks if the provided URI is a URL. If so, retrieve as much information about the project URL as possible (name, description, etc.) using a GET-request and HTML metadata tags.
(See https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta)

This function must be generic and should work on as many websites as possible.
Add this function to the source manager service so it automatically uses this function if the provided URI is an URL and there is no other (more specific) metadata function (GitLab, GitHub etc.) available for the URI.

**Comment by Brend-Smits** [comment]
@StijnGroenen this can be closed right?

**Comment by StijnGroenen** [comment]
> @StijnGroenen this can be closed right?

At the moment the SourceManagerService returns null when the URI does not match a GitLab URL. (See https://github.com/DigitalExcellence/dex-backend/blob/develop/Services/Services/SourceManagerService.cs)
If the URI is an URL, it should make a get request to retrieve metadata about the URL.
This feature is not yet implemented (or at least not merged into develop).

**Comment by Brend-Smits** [comment]
Could you update this issue to be more clear so anyone can puck it up? (Even new DeX members)
Thanks for the follow-up!

**Comment by StijnGroenen** [comment]
> 
> 
> Could you update this issue to be more clear so anyone can puck it up? (Even new DeX members)
> Thanks for the follow-up!

I added some more details to the description of this issue. It should be more clear now.

**Comment by Brend-Smits** [comment]
Thanks, anyone can take on this issue now!
