### ISSUE TITLE
Request 1Password Open Source License

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#137]
Request an open source license for a password manager like 1Password so that we can more easily manage our passwords. We currently use KeepPass but it's not great in my opinion. Especially not in teams with different access levels and requirements.

**Comment by StijnGroenen** [comment]
Also take a look at Bitwarden (a self-hosted password manager) as an alternative to hosted password manager services like 1Password etc.

**Comment by Brend-Smits** [comment]
Waiting for: https://github.com/1Password/1password-teams-open-source/pull/204

**Comment by Brend-Smits** [comment]
Thanks to 1Password we now have an open-source license and we can migrate from KeePass to 1Password.
