### ISSUE TITLE
Project-Update Always returns unauthorized

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#140]
**Describe the bug**
Project Update will always return unauthorized. 
Consider the following code snipper: 
`            string identity = HttpContext.User.GetStudentId(HttpContext);
            bool isAllowed = userService.UserHasScope(identity, nameof(Defaults.Scopes.ProjectWrite));
            User user = await userService.GetUserByIdentityIdAsync(identity);

            if(!(project.UserId == user.Id || isAllowed))
            {
                ProblemDetails problem = new ProblemDetails
                {
                    Title = "Failed to edit the project.",
                    Detail = "The user is not allowed to edit the project.",
                    Instance = "2E765D18-8EBC-4117-8F9E-B800E8967038"
                };
                return Unauthorized(problem);
            }`

In the If statement you're checking the user Identity Id against the Project User Id. This will always be false. 
Most likely this is also the case with other similar checks. 

**To Reproduce**
1. Try to edit you're own project.
2. Get error that you are not authorized to do so.

**Comment by wotwot563** [comment]
This is incorrect, in this if statement it checks if either the user owns the project or has projectwrite scope.

the id that is checked is not the identity id, the identity id is used to get the user object and that user objects id is compared.

**Comment by Brend-Smits** [comment]
> This is incorrect, in this if statement it checks if either the user owns the project or has projectwrite scope.
> 
> the id that is checked is not the identity id, the identity id is used to get the user object and that user objects id is compared.

You're right, my bad. I must have not read it properly due to me being in a hurry! Woops :)
