### ISSUE TITLE
Line ending conflicts

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-backend#163]
Because we agreed on using CRLF line endings, my IDE automatically converts the line endings to CRLF if they aren't already. This is expected and correct behaviour.
The entire code base should have been converted to CRLF after we decided that we were going to use this type on line ending. But apparently the code base still contains files using the LF line endings, which is causing conflicts now (For example PR #162).
I think this is because the default behaviour for Windows developers is that the code uses CRLF locally but commits LF line endings. See screenshot of the Git installer for Windows:
![image](https://user-images.githubusercontent.com/8530165/83518415-b4b7ed80-a4da-11ea-8c31-d0c574757645.png)

I think we have 3 options here:
- Agree on using LF (Unix) line endings and the Windows users can keep this option enabled (Preferred by me since I prefer LF line endings).
- Using the CRLF line endings like we agreed before and disabling this feature for all Windows developers
- We can use a .gitattributes file to make sure that the file in our repository are committed using CRLF line endings

Opinions please. @DigitalExcellence/backend

**Comment by wotwot563** [comment]
i would say that .gitattributes is the best consistent way. then it cannot go wrong every time.

**Comment by JVerbruggen** [comment]
Without having done real research on this topic, I think it is best to use the .gitattributes, since it is, as wotwot563 commented above, the most consistent way to do this. If you decide to not use the default option in your operating system, it will continue to go wrong no matter what, especially if this default option differs over different operating systems. By specifying it in your project I think it will solve the problem.

**Comment by StijnGroenen** [comment]
I agree that is a good idea to enforce the line endings using the .gitattributes file.
@wotwot563, @JVerbruggen and others, would you guys like to change the entire codebase over to CRLF line endings or change the coding guidelines to LF line endings (both types of line endings can be enforced using .gitattributes, LF is the default).

**Comment by wotwot563** [comment]
follow the guideline so CRLF

**Comment by JVerbruggen** [comment]
I think it may be wise to read this article on this rather old topic: https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

**Comment by JVerbruggen** [comment]
Based on these articles there really is no good answer here. The best we can do right now is following the guidelines, and convert to CRLF. Make sure though that this does not include binary files, only text files, since this might corrupt these files.

**Comment by JVerbruggen** [comment]
Use **text eol=crlf** reference https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by Brend-Smits** [comment]
I will be changing the guidelines to LF line endings. This makes life easier. I personally think it was a mistake to go with CLRF. 

In case the .gitattributes will need updating, I will do this as well in the upcoming pull request.
