### ISSUE TITLE
Improve user flow when logging in

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#165]
**Is your feature request related to a problem? Please describe.**
When the user clicks on the login button, they click on the 'FHICT' button, then get redirected to the backend Identity server, where they have to click "Fontys" again. This is quite confusing for the end-user.

**Describe the solution you'd like**
Upon clicking "Login with FHICT" in the frontend, automatically redirect them through the identity server to the Fontys identity server. 
This way the user does not see the unstyled IdentityServer, this will improve usability.

It would be preferred if we could make a general way of handling this so we can easily add "Login with Surfcontext" in the future, without having the user going to our Identity server again. Making a re-usable implementation of this streamlines the future login implementations.

**Additional context**
Some people will still need to login with the "local login" in the identity server, we will probably need a new button for this on the frontend "Login with Identity Server" and a flow that does not redirect them through our Identity Server but that uses the old flow. 

This issue will require changes in both the backend and in the frontend.

**Comment by StijnGroenen** [comment]
The local sign-in would only be used by administrators right? In that case, I think that this should be on a separate page.
If we are going to add support for local users (and registering a Digital Excellence account etc.) than it should be visible on the normal sign-in page.

**Comment by StijnGroenen** [comment]
The local sign-in would only be used by administrators right? In that case, I think that this should be on a separate page.
If we are going to add support for local users (and registering a Digital Excellence account etc.) then it should be visible on the normal sign-in page.

**Comment by wotwot563** [comment]
backend support for a staff panel is already implemented so the new semester shouldnt have that much work on it.
