### ISSUE TITLE
Define architecture for backend

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#17]
In GitLab by @Brend-Smits on Mar 4, 2020, 20:36

Define a scalable architecture. 
Think broad, if we want to scale this. How are we going to do this with the architecture? 
Will a micro-service architecture benefit us?

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 4, 2020, 21:03

closed

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 4, 2020, 21:04

reopened

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 5, 2020, 21:46

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 5, 2020, 21:47

changed title from **{-https://git.fhict.nl/delta-projecten/Digital-Excellence/issues/12-}** to **{+Define architecture for backend+}**

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 5, 2020, 21:47

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 9, 2020, 15:39

I added the C4 model to the wiki.  
https://git.fhict.nl/dex/dex-backend/-/wikis/Software-Architecture/C4-Model

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 22, 2020, 16:19

Last week I also added the specifications of interfaces (https://git.fhict.nl/dex/dex-backend/-/wikis/Software-Architecture/Specification-of-interfaces) and persistence per component (https://git.fhict.nl/dex/dex-backend/-/wikis/Software-Architecture/Persistence-per-component) pages.

These pages also require review. After that this issue can be closed.

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 23, 2020, 12:46

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
