### ISSUE TITLE
Add Postman tests to pipeline

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#189]
**Is your feature request related to a problem? Please describe.**
Postman tests exist, but are not yet executed when a pull request is created

**Describe the solution you'd like**
Add the postman tests to the pipeline and trigger them on pull request

**Additional context**
Postman files can be found in /Postman directory.

**Comment by RensvdLinden** [comment]
I will work on this during the holiday

**Comment by Brend-Smits** [comment]
Postman Tests should be executed in the pipeline; we need to set up a temporary backend in Github Actions, then the postman tests (which will also be executed in the same Github Actions environment) can use "localhost" to communicate with the backend. 
A separate environment will need to be created in Postman to accommodate this change.

**Comment by matir8** [comment]
There's an issue with the certificates set up on the development docker environment. The same problem as #200. The API and the Identity server can't establish HTTPS connection which leads to an authentication error.
