### ISSUE TITLE
Search function is too extensive

### ISSUE THREAD

**Issue by RensNooren** [DigitalExcellence/dex-backend#202]
**Describe the bug**
Search for a single word on the Project Overview page. The words get filtered within entire texts.

**To Reproduce**
1. Go to Project Overview
2. Search "Cat"
3. Get results which should not directly relate to "Cat"

**Screenshots**
https://files.slack.com/files-pri/T0A8LSYA2-F015LPVV65R/screencapture-dex-software-project-overview-2020-06-17-21_55_52.png

**Comment by Brend-Smits** [comment]
In production you can see this 'dumb' search behavior: https://dex.software/project/overview?query=cat
