### ISSUE TITLE
Add display names or full names instead of FHICT names

### ISSUE THREAD

**Issue by MaxKorlaar** [DigitalExcellence/dex-backend#204]
**Is your feature request related to a problem? Please describe.**
When you sign up with your FHICT account, your full name as shown in the FHICT is used, including your initials at the end, and your surname first.

**Describe the solution you'd like**
I'd like my name to be either changeable, an option for a custom display name or that my name is based on my first name + my surname, which the FHICT api offers as well.

**Additional context**
None

**Comment by Brend-Smits** [comment]
We've changed it to be first name + surname. In the future, we might look into making it changeable
