### ISSUE TITLE
The get highlights endpoint returns too much information

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-backend#205]
**Describe the bug**
The [HighlightResourceResult](https://github.com/DigitalExcellence/dex-backend/blob/develop/API/Resources/HighlightResourceResult.cs) class returns the full project model instead of using a resource class. It also includes the start and end date of the highlight. In my opinion, these dates should not be returned (unless we actually want to show them in the front end).

**To Reproduce**
Make a request to the get highlights endpoint.
The start and end dates are returned as well as the full project model.

**Expected behaviour**
The start and end dates should not be returned.
The only project information that should be returned is the information that is actually shown on the highlights page (homepage) in the front end. Like the name and the short description.

**Comment by Brend-Smits** [comment]
With the addition of #218 we only need to return the project id, highlight id, and description I think.
