### ISSUE TITLE
Status code 404 should not be used for empty lists

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-backend#207]
**Describe the bug**
Error code 404 should not be used when there is nothing to return when getting a list. The 400-499 range of HTTP status codes indicate a client error. When the list of highlights is empty, it is not a client error. When the request specifies a specific ID that does not exist. The 404 Not found status code is correct.
In my opinion, status code 200 (OK) with an empty array as the body or status code 204 (No content) should be used.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a request to the get all highlights endpoint when there are no highlights.
2. A 404 Not Found status code is returned

**Expected behaviour**
Status code 200 OK should be returned. The body of this response can contain an (empty) array just like when there are highlights in the database.

**Comment by Brend-Smits** [comment]
The postman tests will also need to be changed accordingly.

**Comment by Brend-Smits** [comment]
This one I really want to get done during this sprint. Anyone that wants to fix this from @DigitalExcellence/backend ?

**Comment by jcoenen96** [comment]
This actually has to be 404 and not 204. This has been discussed multiple times last semester. This has to do that it is an API and not a website.

**Comment by Brend-Smits** [comment]
> This actually has to be 404 and not 204. This has been discussed multiple times last semester. This has to do that it is an API and not a website.

Yes, it was also discussed that it was not practical to enforce this.

**Comment by jcoenen96** [comment]
Then update the issue that this has been discussed. Currently, the issue indicates that the protocol has been implemented incorrectly which is not true. I can't know when something has been discussed when it isn't described in the issue.
