### ISSUE TITLE
Ability to like projects

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#229]
**Is your feature request related to a problem? Please describe.**
There is no way to like projects. We want to implement the ability to like projects. This can be used for other systems like the recommendation algorithm or a filter based on most liked projects.

**Describe the solution you'd like**
A registered user should be able to like a certain project.

- A new endpoint to like a project
- A new endpoint to unlike a project
- New unit tests
- New Postman Integration tests
- Updated documentation on our wiki (like C4 model, persistence per component, etc)

**Comment by aintabb** [comment]
Hi Brend, If it is okay, I would like work on this issue. This could be my first open-source contribution.
What do you think and also what i need to do? I am currently examining the doc and the project.

**Comment by Brend-Smits** [comment]
Hey @aintabb, sure thing! Welcome to DeX. I recommend starting out by reading through our Wiki and getting yourself familiar with that. Once you are set up, assign yourself to an issue and get developing. Open a Pull Request when you're finished so we can review it and provide feedback.
If there's no PR before the upcoming Monday, our team will have to pick it up though, we're on a schedule and work in sprints.

**Comment by aintabb** [comment]
Sounds perfect! Thanks a lot.

**Comment by aintabb** [comment]
Couple questions:
- I am using Ubuntu. Would it be a problem?
- If not, I have managed run docker images and can see the api is running through SwaggerUI but i cannot authorize. When I click authorize, my browser showing me "This site can’t be reached" message.

**Comment by StijnGroenen** [comment]
> Couple questions:
> 
> * I am using Ubuntu. Would it be a problem?
> * If not, I have managed run docker images and can see the api is running through SwaggerUI but i cannot authorize. When I click authorize, my browser showing me "This site can’t be reached" message.
> * As a last thing, do you guys have any IRC channel or discord server which i can communicate with you easily?

I used to work on Digital Excellence using an Ubuntu based distro as well (Pop_OS!). It works fine with some additional setup. Using the Docker development environment it should be very easy though.
Have you seen the Getting Started guide? https://github.com/DigitalExcellence/dex-backend/wiki/Getting-Started
I don't know if it is still accurate, but it could help.

I believe there is a Slack workspace available for easy communication, but most of the communication is done using GitHub.

**Comment by aintabb** [comment]
Hi @StijnGroenen ,
Yeah, I was following the “Getting Started” guide and it seems the docker image is working well.
I think the problem might be related with database. Since I am using Ubuntu, I couldn’t use SQL Server Studio. 
So how I can i connect to database? I am using a built-in database explorer and trying to figure out what should be the connecting string or url?

**Comment by Brend-Smits** [comment]
As Stijn mentioned, Ubuntu should work fine. Especially when running on Docker. But if you're using Rider, everything should work fine as well after you install MSSQL manually. 

The docker development image is a little broken, read more about the fix here #235 . I hope to have it merged today/tomorrow. Nonetheless, you can copy the current changes into your current branch and atleast have the Identity Server working properly :)

In regards to communication, I'm not sure about that yet. This is also the first time we have an 'outside collaborator' so for now, please contact me on Discord: Rubbertjuh#3280

**Comment by aintabb** [comment]
Got it. Thanks. I will keep you guys updated.

**Comment by aintabb** [comment]
@Brend-Smits @StijnGroenen FYI, Now everything works well. Thanks for the guidance.
I was able to send a request to the API and get the result.
Because of the time zone differences, i am responding your messages late. I live in Los Angeles.
I am gonna speed up and work on the issue now and again will keep you updated.

**Comment by StijnGroenen** [comment]
> As Stijn mentioned, Ubuntu should work fine. Especially when running on Docker. But if you're using Rider, everything should work fine as well after you install MSSQL manually.
> 
> The docker development image is a little broken, read more about the fix here #235 . I hope to have it merged today/tomorrow. Nonetheless, you can copy the current changes into your current branch and atleast have the Identity Server working properly :)
> 
> In regards to communication, I'm not sure about that yet. This is also the first time we have an 'outside collaborator' so for now, please contact me on Discord: Rubbertjuh#3280

I used Rider as my IDE. Before we had the Docker development environment, I had to install SQLServer. I also had to change the connection string since LocalDb did not work on my device. All of those things should not be necessary anymore if you get the Docker development environment working.



> @Brend-Smits @StijnGroenen FYI, Now everything works well. Thanks for the guidance.
> I was able to send a request to the API and get the result.
> Because of the time zone differences, i am responding your messages late. I live in Los Angeles.
> I am gonna speed up and work on the issue now and again will keep you updated.

Great to hear!
