### ISSUE TITLE
Research: Designing a plugin-like system for Wizards

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#239]
**Is your feature request related to a problem? Please describe.**
Wizards are going to be a big part of the DeX platform. We don't want to have to redesign the whole system when a new different source is requested.

**Describe the solution you'd like**
We should research how existing applications implement this and solve this issue. Example applications are Microsoft Teams (apps), but also Canvas and other applications. 
We don't want to reinvent the wheel, research into existing design patterns that can help solve this problem. 

We want to implement sources like Codepen, Canvas, Github, Gitlab, without having to rewrite parts of the code constantly. It might be nice to have these resources running independently and just have an API available for people to use. The sources could then be implemented in a completely different language if wanted. This way we de-couple things. We have to think about this as it brings on additional challenges of course. 

**Additional context**
Check Frontend issue https://github.com/DigitalExcellence/dex-frontend/issues/319 for designs

**Comment by Brend-Smits** [comment]
We should look into picking this up as a group and design a system for this @DigitalExcellence/backend

**Comment by niraymak** [comment]
We agreed on a general architecture and will start working on 2 implementation. We will discuss these implementations later this week to make sure the architecture is right and will work for multiple implementations.

Ruben and Dave will work on Github implementation.
For Github implementation it is required to use oauth flow to see private repositories.

Niray and Mees will work on JSFiddle implementation.
There is no oauth flow required for this.

**Comment by niraymak** [comment]
Documentation related to this project can be found in the link beneath: 
https://docs.google.com/document/d/1P6SJc6jy4Xi4XOfpW0R7o9nMidDFWA5z5aXkzCt1g1c/edit?usp=sharing

**Comment by Brend-Smits** [comment]
Is this issue considered done? Or can I move it to Sprint 8?

**Comment by MeesvanStraten** [comment]
Done

**Comment by niraymak** [comment]
Research documentation:

https://docs.google.com/document/d/1P6SJc6jy4Xi4XOfpW0R7o9nMidDFWA5z5aXkzCt1g1c/edit?usp=sharing
