### ISSUE TITLE
Research: Investigate best way to send emails / what provider to use

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#242]
**Is your feature request related to a problem? Please describe.**
We want to send emails, but preferably don't want our own email server (managing email reputation is tricky and too time consuming). 

**Describe the solution you'd like**
A research conducted to learn what email providers there are, what they offer in terms of feature, what their pricing is(preferably free) and if they have integrations with C# .NET Core. 
The email provider must allow the use of dynamic content (we need to be able to add dynamic content in the emails), must be able to use a custom domain with the provider. Must be a reputable vendor. Other requirements you can think of yourself, discuss with me once you have a final list. 

**Additional context**
Examples are: Mailgun, Sendgrid
This issue is great if you need certain KPI's from Software.

**Comment by waltersajtos** [comment]
The research can be found [here](https://docs.google.com/document/d/1Sp3q3SjBT2Xd4U_nws0aDvIgv9Mb75mAJ5rGRkp9tC0/edit)

**Comment by Ruby77** [comment]
The final version of the research can be found [here](https://docs.google.com/document/d/1Sp3q3SjBT2Xd4U_nws0aDvIgv9Mb75mAJ5rGRkp9tC0/edit).

The conclusion of this research is to use Sendgrid. You can work easily with this provider, integration is also easy and they have a good reputation. For the free version, you can send 100 emails per day completely free. So make sure there is a good distribution of emails to minimize the costs for this provider. For the full conclusion, read the research.
