### ISSUE TITLE
Research & Design: Ability to only show project/ideas to my own school

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#249]
**Is your feature request related to a problem? Please describe.**
Certain projects/ideas are limited to a specific institution. A reason can be that they are only relevant to that institution or that they are not allowed to be shared outside of the institution.

**Describe the solution you'd like**
When a user logs in we know what school/district they come from. Maybe we need to save this information if we don't do this already. Based on this information we add the following:
- When adding a project, show a checkbox: "[x] Only show this entry for **Fontys**"
- This entry will not be shown to guests or people outside of the institution.
- Filter to only shown entries for your institution.

**Additional context**
This issue is about conducting research on how we should accomplish this and what needs to be changed in our current system to make this functionality possible. Updating system designs is also part of this issue.
Think about edge cases as well, what if a guest uses a link to a 'semi-private' entry. Should we restrict access? Also, what about the search engine, should we index these 'semi-private' entries?

**Comment by Yuqera** [comment]
This is the first recommendation I have for the private institute project.
[private-institute-projects.docx](https://github.com/DigitalExcellence/dex-backend/files/5465312/private-institute-projects.docx)

**Comment by Brend-Smits** [comment]
Please create a Google Docs file @Yuqera so users can give feedback. Using Google Docs is our standard.

**Comment by Yuqera** [comment]
@Brend-Smits here is the Google Docs file so I can receive feedback. https://drive.google.com/file/d/1GyYE5gMA5mgk2rm4sKewP-4Y9JECb5pP/view?usp=sharing

**Comment by Yuqera** [comment]
@Brend-Smits Here is the document in Google Docs https://drive.google.com/file/d/1GyYE5gMA5mgk2rm4sKewP-4Y9JECb5pP/view?usp=sharing

**Comment by Brend-Smits** [comment]
> @Brend-Smits here is the Google Docs file so I can receive feedback. [drive.google.com/file/d/1GyYE5gMA5mgk2rm4sKewP-4Y9JECb5pP/view?usp=sharing](https://drive.google.com/file/d/1GyYE5gMA5mgk2rm4sKewP-4Y9JECb5pP/view?usp=sharing)

The file is not in our drive and thus I can't access it. Put it in the Digital Excellence Drive.

**Comment by Brend-Smits** [comment]
I've provided feedback in the document. I don't think it's finished yet, I've added it to Sprint 7.

**Comment by Yuqera** [comment]
@Brend-Smits I've processed your feedback if you could please take another look when you're available.

**Comment by Brend-Smits** [comment]
> @Brend-Smits I've processed your feedback if you could please take another look when you're available.

I provided additional feedback :)

**Comment by Yuqera** [comment]
> > @Brend-Smits I've processed your feedback if you could please take another look when you're available.
> 
> I provided additional feedback :)

I've processed the additional feedback!

**Comment by Brend-Smits** [comment]
This can be considered done, do you agree @Yuqera ?
If so, can you make sure that there are issues in both the backend and frontend describing what is needed in terms of development?
