### ISSUE TITLE
Research - Create a request for Hosting - Be specific what is needed and what is expected

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#250]
**Is your feature request related to a problem? Please describe.**
We need Fontys to pay for hosting as soon as possible. Fontys wants to know what to expect for hosting, why others are not sufficient, and what has been tried.

**Describe the solution you'd like**
We already have a simple, and small research regarding hosting and what is needed. This needs updating and cleaning up. Also needs updating with the latest requirements and pricing.  

**Additional context**
Fontys wants to know what to expect for hosting, why others are not sufficient, and what has been tried.
Please don't make new research, but continue from the previous 'research' found in the google drive. Depending on my schedule, I can help with researching and will provide continuous feedback.

**Comment by Brend-Smits** [comment]
@elmiratjee let's wrap this up upcoming Tuesday or Friday (depending on when you're next on location). Can you schedule a meeting please?

**Comment by elmiratjee** [comment]
@Brend-Smits  Are you also on Wednesday on location? Otherwise, it would be Friday :)

**Comment by Brend-Smits** [comment]
Finished and send to correct people https://docs.google.com/document/d/1-UasWhxTVADF0VPBJO7W_-RvKlSLD-M4t-jaqxYoxi8/edit?usp=sharing
