### ISSUE TITLE
Research message broker

### ISSUE THREAD

**Issue by Maxvanhattum** [DigitalExcellence/dex-backend#253]
**Is your feature request related to a problem? Please describe.**
To get the notification system up and running a messagebroker is going to be needed which load balances and keeps track of data. For this research is needed

**Describe the solution you'd like**
A research report is needed which describes what the messagebroker needs to be able to do, compares different messagebrokers and ultimately suggest the best one the should be used. This also entails the way on how to approach the messagebroker, eg polling or pub/sub.

**Additional context**

**Comment by Maxvanhattum** [comment]
@Brend-Smits https://drive.google.com/file/d/1C1L6Cs5hQu7KXpJAJt9Clwq0TdHFisoG/view?usp=sharing

**Comment by Brend-Smits** [comment]
LGTM! Feedback for next time:
- Add a Management Summary

Please create issues if needed based on your conclusions.
