### ISSUE TITLE
Designing the notification system

### ISSUE THREAD

**Issue by Maxvanhattum** [DigitalExcellence/dex-backend#255]
**Is your feature request related to a problem? Please describe.**
The notification system needs to be designed and worked out so that it fits into the current design document. 

**Describe the solution you'd like**
The design needs to entail the new endpoints, back-end logic, database tables/columns, messagebroker, background service and email service API. The current design document needs to be updated so that it's up to date before the notification feature can be implemented.  

**Additional context**
This issue can be started only *after* the research has been done.

**Comment by Maxvanhattum** [comment]
@Brend-Smits @MeesvanStraten 
Please review :) https://drive.google.com/file/d/10iH2Z80MzR3aLKWOcGFo6Hj8Es3szzJQ/view?usp=sharing

**Comment by Brend-Smits** [comment]
The C4 design looks great, please update it on the wiki as well so everything is in sync. 
Let's move on to implementation! Good job 👍🏼

**Comment by niraymak** [comment]
Research and documentation will be updated during implementation.
