### ISSUE TITLE
Implementing notification system

### ISSUE THREAD

**Issue by Maxvanhattum** [DigitalExcellence/dex-backend#256]
**Is your feature request related to a problem? Please describe.**
A notification systeem needs to be implemented, according to the designs. It needs to be able to track which users need to be notified for whatever notification that has to be send out, eg a new project from a user they follow, newsletter, GDPR updates etc. Moreover it needs to be able to send these notifications through different methods.

**Describe the solution you'd like**
The designs previously come up with need to be implemented. This entails new endpoints, additional or modified entities, new logic to handle registering notifications and to immediately set notifications to be displayed in the front-end, communication with a messagebroker, a standalone service which approaches the messagebroker and send the data to the specified way of notifying the user. 

**Additional context**
This can be done only *after* the research and designing has been done.

**Comment by niraymak** [comment]
Issue will be implemented as mentioned in the research below.
https://drive.google.com/file/d/1C1L6Cs5hQu7KXpJAJt9Clwq0TdHFisoG/view?usp=sharing
