### ISSUE TITLE
Convert Backup script to Docker container

### ISSUE THREAD

**Issue by RensvdLinden** [DigitalExcellence/dex-backend#257]
**Is your feature request related to a problem? Please describe.**
The backups of the db are now pushed to OVH Cloud through a script, which is ran through a cron job. It's better to throw this in a docker container, which can be added to the docker-compose, so migrating becomes easier.

**Describe the solution you'd like**
Create a Docker container that's responsible for the OVH Cloud backups of the db

**Comment by aintabb** [comment]
How about me picking this up? @Brend-Smits @RensvdLinden

**Comment by Brend-Smits** [comment]
@aintabb Awesome to see that you're willing to pick it up, sadly this is reserved for @elmiratjee so she can learn the infrastructure as part of her education. 

In general, things that require backend access (access to physical servers), are off-limits for outside collaborators. I will be creating new issues today/tomorrow.

**Comment by aintabb** [comment]
@aintabb No worries! Thanks for the clarification. Good luck @elmiratjee
