### ISSUE TITLE
Documentation: Access Level Control

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#266]
**Is your feature request related to a problem? Please describe.**
It is not clear what roles (should) have access to what permissions.

**Describe the solution you'd like**
Create a wiki entry and document all the different roles and scopes and explain what it has access to. It should be kept simple and clean so it's easy to maintain.

**Comment by waltersajtos** [comment]
I created a [wiki page](https://github.com/DigitalExcellence/dex-backend/wiki/Permissions)
