### ISSUE TITLE
Design: User portfolio system

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#268]
**Is your feature request related to a problem? Please describe.**
As a user I want to create, customize and setup my personal portfolio.

**Describe the solution you'd like**
Design a system where users can create, customize, and delete portfolio items. 
By default portfolio items will include: 
- Projects you added to the platform
- Basic profile information
But users should also be able to link their contact information, social media (linked-In), and Github/Gitlab.
Users can add formatted text sections to tell a visitor something about his/herself. 
Users should be able to decide per project if they want to show/hide it on their profile.

We should design the system in a way that is easily expandable in the future as portfolios will be expanded in the future. 

**Additional context**
This issue is focussed on system design, how are the above requirements going to translate into our backend? Once this has been determined, the developer that picks up this issue can create new issues based on these findings (please talk with me first)

**Comment by Brend-Smits** [comment]
I would highly prefer it if people worked together on this issue. It's crucial that this is designed properly.

**Comment by DaveBouman** [comment]
Walter and I talked about the best way to implement the portfolio system. We made a document in which we described the best solution. https://docs.google.com/document/d/1Mn9V-PEDcCH6LsAMN2EKRk22hnr-xfZyK9teUGETArU
