### ISSUE TITLE
Research: Student Graduation detection

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#269]
**Is your feature request related to a problem? Please describe.**
Students graduate... Some may still want to be active on the platform afterward. Currently, they will no longer be able to log in when their institution account gets deactivated. 

**Describe the solution you'd like**
Research how we can determine when a student is graduating, based on this we can notify them by email or something asking them what they want to do with their account. 
1. Keep it as it is, don't remove the data.
2. Convert the account to status "alumni" and require them to set a new email & password. They will be able to login in the future using the new credentials.

We might need a new role for use-cases like these. I surely don't want to lose access to my account when I graduate. When your research is complete, deliver it to me and we can discuss if and how we want to move forward with implementation.

**Additional context**
Please work together on this issue, it's quite large.

**update 26-10-2020**
After discussing research with Brend we are moving to implementing this issue and we will make use of Service Workers to schedule tasks. The implementation will be done in a new issue.

**Comment by niraymak** [comment]
https://docs.google.com/document/d/1YVOhW3eA59eH52cCVTfA9HxJZKebTR9fr_Ehqbuzbe8/edit?usp=sharing
