### ISSUE TITLE
Research: Security on storing files

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#273]
**Is your feature request related to a problem? Please describe.**
There was no research done for the current implementation of the fileuploader. Currently only project icons are stored. These project icons are currently accessible for everyone but in the future files may be stored which are sensitive. Therefore we should do some research if the implemented feature is safe. Uploading files may also bring other risks.

**Describe the solution you'd like**
Research if the created solution is safe. If not research how we should improve security for uploading files.

**Additional context**
https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload

**Comment by matir8** [comment]
https://drive.google.com/drive/u/0/folders/1LvKiy68B6p-9hX7z6_ZjZg8K9nqtDtwr

**Comment by Brend-Smits** [comment]
Looks great, thanks for the research ^^
