### ISSUE TITLE
Research: tooling for recommendation system

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#275]
**Is your feature request related to a problem? Please describe.**
To implement a suitable recommendation system it is useful to answer the following questions:
“What tools can contribute to the implementation of a project recommendation system?”
“What can the tools contribute?”
“What are the advantages and disadvantages of this tool against an own implementation?”

**Describe the solution you'd like**
The above mentioned questions are answered (following the DOT framework guidelines) and reported in a document.

**Additional context**

**Comment by niraymak** [comment]
https://docs.google.com/document/d/1zp8BL5G6pvrBf_WLU5MB8bVqNMbwzxP-ozAZi3FSNSs/edit?usp=sharing

**Comment by Brend-Smits** [comment]
When do you expect this to be finished @niraymak ?

**Comment by niraymak** [comment]
I still want to add documentation to this document about how we connect our database to ElasticSearch database but will do that in a seperate document. So I will close this one.
