### ISSUE TITLE
Research: what data should be used for recommending

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#277]
**Is your feature request related to a problem? Please describe.**
To find out what data we should use for the recommendation system we could answer the following questions.
“What data is already stored which can be used to implement a recommendation system?”
“What data has added value for implementing a recommendation system for DeX?”

Does anyone have experience with a similar kind of research? 
I was thinking of interviewing people about what they think are important factors / data they should be recommended on. 
I am not sure yet if this will lead in 'hard' results on what data we should use.

**Describe the solution you'd like**
The above mentioned questions are answered (following the DOT framework guidelines) and reported in a document.

**Additional context**
http://ictresearchmethods.nl/The_DOT_Framework

**Comment by Brend-Smits** [comment]
When do you except to finish this issue @niraymak ?

**Comment by niraymak** [comment]
> When do you expect to finish this issue @niraymak ?

Still need to work on the documentation. Conclusion is to start using collaborative filtering using project likes and recommend on base of that.

**Comment by niraymak** [comment]
Research can be found in the link below:

https://docs.google.com/document/d/1B1u_j5jQXmv3GVPG-HrXYJLR8rVKbtAhEkLjbac6KSs/edit?usp=sharing
