### ISSUE TITLE
On user sign up, the institution should be linked

### ISSUE THREAD

**Issue by Ruby77** [DigitalExcellence/dex-backend#295]
**Is your feature request related to a problem? Please describe.**
After implementing the data officer issue (https://github.com/DigitalExcellence/dex-backend/issues/265), institutions can be added to users. However, this still doesn't happen for users. Whenever a new user signs up, it should check if the institution is already added to the DeX system. If it's already added, then the user should be linked to this institution. 
For the already existing users, they should also be updated to link them to institutions that are added.

**Describe the solution you'd like**
When the user signs up or logs in, there should be a check, to see if the institution they use to log in has been already added to the DeX platform. If the answer is yes; the user should be linked to this institution.

**Additional context**
Blocked until the data officer issue (https://github.com/DigitalExcellence/dex-backend/issues/265) is merged to develop.

**Comment by Brend-Smits** [comment]
This can be done in the same way the user is currently added to the backend in the identity server. When the user logs in you can make a request to the API to add an institution. The provider name/id can be used. This provider is retrieved from the Identity Server (each provider has a unique id and returns a provider name as well).
