### ISSUE TITLE
Project Icon not loading on production

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#298]
**Describe the bug**
Project Icons / Files are not loading on staging after uploading a new project icon. This is likely because of using the wrong paths (windows style vs Linux).

**To Reproduce**
1. Go to staging.dex.software.
2. Create a project and upload a file
3. Navigate to the project and see 404 on image.

**Expected behavior**
Working project icon

**Screenshots**
![image](https://user-images.githubusercontent.com/15904543/98347182-59ed6980-2017-11eb-94fb-4920f8281928.png)

**Comment by niraymak** [comment]
mentioned isssue was fixed in pull request below

https://github.com/DigitalExcellence/dex-backend/pull/300
