### ISSUE TITLE
Wiki: Postman instructions

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#299]
**Is your feature request related to a problem? Please describe.**
Currently it is not clear how Postman testing works for DeX. We should update the Wiki so we can refer to that if there is any questions about Postman.

**Describe the solution you'd like**
A Wiki page with extensive explanation of how Postman testing works within DeX.

**Additional context**

**Comment by waltersajtos** [comment]
Topic that were unclear to me:

- [ ] Postman environments (import again after every merge, save manually)
- [ ] Postman collections (import again after every merge, save manually, replace file urls)
- [ ] Don't re-use variables (explain how to add new ones)

**Comment by Brend-Smits** [comment]
https://github.com/DigitalExcellence/dex-backend/wiki/Postman-guide
