### ISSUE TITLE
Feature Institute private projects

### ISSUE THREAD

**Issue by Yuqera** [DigitalExcellence/dex-backend#310]
**Is your feature request related to a problem? Please describe.**
While using the DeX platform, all the projects I create will be public to see for everyone. I cannot publish my projects only for my institute and I cannot see the projects created by others from my institute.

**Describe the solution you'd like**
When logging into DeX your institute gets saved to your account. Please reference the documentation (#249) for further implementation into the backend.

**Additional context**
Blocked until the documentation (#249) has been accepted and the feature (#295) has been merged to developer.

**Comment by Brend-Smits** [comment]
I think we can move onto implementation with this, correct @Yuqera ?

**Comment by Yuqera** [comment]
@Brend-Smits this can indeed be moved onto implementation.
