### ISSUE TITLE
Add "Call-to-Action" to the backend

### ISSUE THREAD

**Issue by Ruby77** [DigitalExcellence/dex-backend#312]
**Is your feature request related to a problem? Please describe.**
Currently, the front-end created an implementation for the Call-to-Action issue. Unfortunately, this issue also needs to connect to the backend and in the back-end, there is no implementation yet, and so, it blocks the issue from merging.

**Describe the solution you'd like**
A project also needs to store a possible existing call to action with a link and content in the call to action button. 

**Additional context**
[The call to action issue on the front-end](https://github.com/DigitalExcellence/dex-frontend/issues/267)

**Comment by Ruby77** [comment]
I will create the functionality to manage the default names for the call to action. Which roles should be able to do this @Brend-Smits ?

**Comment by Brend-Smits** [comment]
Administrator @Ruby77

**Comment by Ruby77** [comment]
@Brend-Smits but all the roles should have the read scope for reading the options, right? Just to make sure 😄!
