### ISSUE TITLE
Wiki + Update SAD (Software Architecture Document)

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#323]
**Is your feature request related to a problem? Please describe.**
The SAD might be outdated, it was created last semester but a lot has changed since then.

**Describe the solution you'd like**
Update the Software Architecture Document and upload it on the drive.

**Additional context**
Please don't rewrite everything, add sections and update parts that are outdated ;)
When finished, please create a wiki submission in the backend linking to the document download for instance.

**Comment by mmerel** [comment]
I would like to be informed of the result. I need this to talk to other colleagues on how Dex can become more prominent in FHICT Fontys.

**Comment by Brend-Smits** [comment]
Hey @Ruby77, how is this going?

**Comment by Ruby77** [comment]
Via this link, you can find our [Software architecture document wiki page](https://github.com/DigitalExcellence/dex-backend/wiki/Software-Architecture-Document). On this page you can learn the basics of our underlying architecture. For more information, the wiki page links our [created software architecture document on Google Drive](https://docs.google.com/document/d/1VH_h2MH5A7Smu_3S8B8KjOkWKSW0C7JZr4-Emsgvv0E/edit?usp=sharing) for the complete document with diagram explanations and extra information.
