### ISSUE TITLE
Wiki - Infrastructure Documentation

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#324]
**Is your feature request related to a problem? Please describe.**
There is documentation of the infrastructure somewhere, but it's not linked in the Wiki.

**Describe the solution you'd like**
Find the infrastructure document, update it, or create it. Then link it in a new or already created Wiki sidebar submission in the backend.
Infrastructure documentation should explain briefly how the current infrastructure looks and works.

**Comment by elmiratjee** [comment]
Here the end result after the feedback: 
https://github.com/DigitalExcellence/dex-backend/wiki/Explanation
