### ISSUE TITLE
Wiki - What tools do we use?

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#325]
**Is your feature request related to a problem? Please describe.**
There is no documentation/overview on what tools DeX uses and for what purpose they are used.

**Describe the solution you'd like**
A single wiki page to explain what tool is used and for what purpose. Tools that we use that should be described:
- Postman
- Sentry
- 1Password
- SonarQube
- Cloudflare
I might be missing some.

**Additional context**
Create a wiki submission for both the frontend and the backend

**Comment by niraymak** [comment]
https://github.com/DigitalExcellence/dex-backend/wiki/What-tools-do-we-use%3F

**Comment by niraymak** [comment]
Wiki added for SonarQube, Postman and Sentry. Not sure why we use 1Password and Cloudflare. Waiting for feedback on that.

**Comment by niraymak** [comment]
Wiki finalized. 1Password and Cloudflare may be a bit short. Please review and provide me with feedback if necesarry.

**Comment by Brend-Smits** [comment]
Postman:
Please add a link to more detailed information about postman testing (the guide you wrote).

The rest looks great, nice work. Once you added the link, you can close this issue.

**Comment by niraymak** [comment]
Done :)
