### ISSUE TITLE
Postman cleanup / equalize naming conventions for variables

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#328]
**Describe the bug**
Currently not all added entries during Postman integration tests are deleted on cleanup.
They are also only succeeding only iteration. 
To get a better structure we should start using a guide which makes sure are tests are written the same way. 

In my opinion in the cleanup folder at the end all leftovers should be deleted with administrator credentials. In my opinion variables should not be reused in various tests, but this is something to discuss as we probably need to write more tests to fix this. More tests means also a longer duration for the pipeline.

**To Reproduce**
1. Run API / IdentityServer
2. Run postman tests
3. Check database, for example Projects table.

**Expected behavior**
After running Postman tests the database should like the same as before running the tests.
All tests be able to run multiple iterations.

**Screenshots**
Project table after running one iteration:
https://gyazo.com/fe1420bfcf766b8f1c00e1b1c9c94f37
Second iteration: 
https://gyazo.com/2b50aa91157f61453c92f53454b5bbcc

**Production URL**

**Additional context**
We should add naming conventions in the Postman guide.

**Comment by Ruby77** [comment]
Also, verify the naming conventions. I've seen multiple different naming conventions appear in the tests.

**Comment by Ruby77** [comment]
I will continue working on this, however, I have another big issue that more priority so I have less time for this issue. So for the people who would like to work on this issue, you can start working on it😄. Send me a message so we can discuss some things I already created.
