### ISSUE TITLE
Improvements on the Notification System

### ISSUE THREAD

**Issue by Maxvanhattum** [DigitalExcellence/dex-backend#337]
**Is your feature request related to a problem? Please describe.**
There are a few things that can be changed to make the notification system more SOLID. These changes will make expanding the system with different methods of sending notifications more easy.

**Describe the solution you'd like**

- In the _MessageBrokerPublisher_ class library introduce a config with appsettings.json (see _NotificationSystem_ ).
- In the _NotificationSystem Program.cs_, introduce a NotifcationServiceFactory class which creates the needed NotificationMethod based on an environment variable (now only Email)
- In the _NotificationSystem_ Introduce a parse method for the _INotificationService_ interface
- In the _NotificationSystem_ Move parsing the messagebody from _CreateConsumer_ method to the new method in EmailSender, and call this instead.

**Comment by Maxvanhattum** [comment]
We've (@niraymak) already done this partly in the branch /feature/62-recommendationsystem. We have some notions about how to best approach this and need to discuss this with @Brend-Smits. Therefore this issue will be blocked until further notice.

**Comment by Brend-Smits** [comment]
@Maxvanhattum Status?

**Comment by Maxvanhattum** [comment]
Should be closed, most of these are obsolete or done. Only one small thing still needs to be done, I'll make a new issue of it.
