### ISSUE TITLE
Searching for a project does not include collaborators

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#340]
**Describe the bug**
https://api.staging.dex.software/api/search/internal/dotnet?query=dotnet&amountOnPage=12&sortBy=updated&sortDirection=desc
Will give the following result: 
```{"results":[{"id":16,"name":"awesome-dotnet","shortDescription":"A collection of awesome .NET libraries, tools, frameworks and software","collaborators":[],"created":"2020-11-20T10:32:35.6602723","updated":"2020-11-20T10:32:35.6605989","user":{"id":2063,"name":"Brend Smits","email":"<Redacted>"},"projectIcon":null,"callToAction":null}],"query":"dotnet","count":1,"totalCount":1,"page":null,"totalPages":1}```
Even though the project has over 20 collaborators.

**To Reproduce**
1. Go to staging.dex.software
2. Search for "dotnet"
3. See collaborators count 0

**Expected behavior**
Collaborators are included.

**Comment by liekevdvoort** [comment]
I think the creator of the project also is included this would be nice to also be included in this issue

**Comment by Brend-Smits** [comment]
> I think the creator of the project also isn't included in the results this would be nice to be included in this issue

````"user":{"id":2063,"name":"Brend Smits","email":"````

I think it is included, or do you mean something else?
