### ISSUE TITLE
Define interface for Search

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#35]
In GitLab by @Brend-Smits on Mar 9, 2020, 21:42

Create an interface together with at least a single 'senior' developer that can be used to create the search controller, service and manager.

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Mar 16, 2020, 13:09

assigned to @StijnGroenen

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Mar 23, 2020, 12:34

Hier te vinden: [Search wiki](https://git.fhict.nl/dex/dex-backend/-/wikis/Software-Architecture/Search-specification)

**Comment by Brend-Smits** [comment]
In GitLab by @wotwot on Mar 23, 2020, 14:26

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to @jcoenen96 because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
