### ISSUE TITLE
Search API Controller

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#36]
In GitLab by @Brend-Smits on Mar 9, 2020, 21:44

Blocked, #33 should be finished before starting this.

* Create the search controller based on #33 
Ensure that proper error handling is used and that the endpoints are following REST Standard as much as possible

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 9, 2020, 21:48

changed title from **Search Controller** to **Search {+API +}Controller**

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 26, 2020, 11:03

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 27, 2020, 11:58

mentioned in merge request !11

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 19:32

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
