### ISSUE TITLE
Search Service

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#37]
In GitLab by @Brend-Smits on Mar 9, 2020, 21:46

Blocked, #33 should be finished before starting this.

* Create a search service based on #33
* Define and create unit tests

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 9, 2020, 22:39

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 9, 2020, 22:41

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 23, 2020, 15:46

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 27, 2020, 11:58

mentioned in merge request !11

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 27, 2020, 12:21

Search service is created.
Unit tests are not (yet).

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 19:32

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
