### ISSUE TITLE
Bug: Inefficient use of entity framework in GetAllWithUsersAndCollaboratorsAsync() (in the ProjectRepository)

### ISSUE THREAD

**Issue by TimSnoek123** [DigitalExcellence/dex-backend#376]
**Describe the bug**
The function GetAllWithUsersAndCollaboratorsAsync() in the ProjectRepository implements a really inefficient way of getting data. This should be improved by using .include(). With 5000 projects using .include() takes around 300 ms and the current way of getting the data takes around 1900 ms. (and even with less data it is around 70% faster)

**Screenshots**
![image](https://user-images.githubusercontent.com/45255534/108855840-b0dc7600-75e9-11eb-8b30-352eb846c2c7.png)
As you can see above for every project 2 additional queries are called in order to get the collaborators and the likes. Using include only executes one query which is way faster especially when getting lots of data.

**Comment by Brend-Smits** [comment]
This is very strange. The results I got when testing this were the other way around. Are you sure the data set that you tested with includes likes and collaborators? 
See: https://github.com/DigitalExcellence/dex-backend/pull/335

**Comment by TimSnoek123** [comment]
The data did have collaborators but not likes, I will try testing it again tomorrow again I guess with more relational data.

**Comment by Brend-Smits** [comment]
> The data did have collaborators but not likes, I will try testing it again tomorrow I guess with more relational data.

Still, the results should be the other way around... unless something has changed in terms of packages that got updated to fix this issue. 
How many collaborators were included per project? (Average)

**Comment by TimSnoek123** [comment]
I just created 5000 projects each with: 7 collaborators and one like.

The include took around: 7 seconds.
The old version took around: 23 seconds.

**Comment by Brend-Smits** [comment]
Well, that sounds good then! I'm glad to hear the issue is resolved. Nice😀

**Comment by TimSnoek123** [comment]
Yes! Maybe Microsoft updated EF or something ¯\_(ツ)_/¯

**Comment by RamonPeek** [comment]
Just validated the behaviour on my machine. Old code takes about 70ms to execute for 30 projects (with collaborators), and the improved code takes about 15 to 20 ms. I also included the likes and Redacted user, so only one SQL query has to be executed each time the projects are retrieved. This second include takes another 3 to 5ms from the response time.

I'll push the changes and open a PR for it.
