### ISSUE TITLE
Add Fontys' Gitlab data source to the wizard

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-backend#377]
**Is your feature request related to a problem? Please describe.**
Currently the implementation of the wizard supports 3 data sources (Github, Gitlab and JsFiddle). Gitlab only supports main Gitlab and not the Fontys Gitlab variant. This data source should be added. 

Update the wizard so that Fontys' Gitlab gets supported as well. When creating support for this, it's important to keep programming principles in your mind (DRY, but also SOLID, KISS, etc.). Don't Repeat Yourself. All the logic for the main Gitlab data source is already written. Research if the logic that's already written can get reused.

**Describe the solution you'd like**

**Additional context**

**Comment by TimSnoek123** [comment]
Kwa code hoeft er weinig aangemaakt te worden want de gitlab datasource class kan gewoon geinherit worden. Ik heb nu aan Marcel Narings gevraagd voor gitlab api credentials.

**Comment by RubenFricke** [comment]
@TimSnoek123 Try to avoid dutch 😉 . An English student will join our project and he has to be able to understand the comments on all the issues.

Tim says: `We don't have to create a lot of new code because the original GitLab data source can get inherited. He requested the FHICT GitLab API credentials by Marcel Narings`.

**Comment by TimSnoek123** [comment]
I created a dex account to test the gitlab functionality. The Get all projects from a specific user seems to be working.

Getting a project by a specific endpoint returns 404 not found when you are not logged in as a user as you can see [here](https://git.fhict.nl/api/v4/projects/I414224%2Fontbossing). If you log into the fhict gitlab the project becomes visible.

Getting a project by a specific id returns some weird JSON where the description is the login page of FHICT?
`{
  "id": 19845,
  "name": "Gamehub-Client",
  "description": " <!DOCTYPE html>\r\n<html lang=\"en-US\">\r\n    <head>\r\n        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=1\"/>\r\n        <meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" />\r\n        <meta http-equiv=\"cache-control\" content=\"no-cache,no-store\"/>\r\n        <meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n        <meta http-equiv=\"expires\" content=\"-1\"/>\r\n        <meta name='mswebdialog-title' content='Connecting to Fontys Hogeschool ICT'/>\r\n\r\n        <title>Sign In</title>\r\n        <script type='text/javascript'>\r\n//<![CDATA[\r\nfunction LoginErrors(){this.userNameFormatError = 'Enter your user ID in the format \\u0026quot;domain\\\\user\\u0026quot; or \\u0026quot;user@domain\\u0026quot;.'; this.passwordEmpty = 'Enter your password.'; this.passwordTooLong = 'Password is too long (\\u0026gt; 128 characters).';}; var maxPasswordLength = 128;\r\n//]]>\r\n</script>\r\n\r\n<script.....",
  "shortDescription": "",
  "uri": null,
  "collaborators": [],
  "projectIcon": null
}`

**Comment by TimSnoek123** [comment]
The login before you can get the data also applies for that weird JSON.
