### ISSUE TITLE
Research: Research a way to perform automated performance tests

### ISSUE THREAD

**Issue by TimSnoek123** [DigitalExcellence/dex-backend#379]
**Is your feature request related to a problem? Please describe.**
As you can see in this issue: https://github.com/DigitalExcellence/dex-backend/issues/376. We found out that the current use of getting projects can be optimized to be faster. Other developers however found that the current use of getting projects is faster. Due to this difference it is hard to know the exact performance of the application.

**Describe the solution you'd like**
Research a way to automate performance tests for production (and other) servers.

**Comment by niraymak** [comment]
Currently we have different resources on staging and production. 
On staging we use the value plan and on production essentials plan.
https://www.ovhcloud.com/en/vps/

It might be a good idea to make these environments the same. Please take this in account in your research.

Also keep in mind that there is a PR incoming including ElasticSearch. #359 This might use some more resources than expected.

**Comment by Brend-Smits** [comment]
Isn't this where Postman can come in handy once again? Or are you looking for specific EF Core automated performance tests?
