### ISSUE TITLE
Basic search functionality

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#38]
In GitLab by @Brend-Smits on Mar 9, 2020, 22:35

Implement a basic search functionality so that we can search for projects and implement a search bar on the frontend.
Try to keep the feature expandable so we can easily replace or expand it in the future when implementing more complex search functionality/algorithms (#27)

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 9, 2020, 22:35

assigned to @Brend-Smits

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 16, 2020, 11:16

unassigned @Brend-Smits

**Comment by Brend-Smits** [comment]
In GitLab by @RensvdLinden on Mar 18, 2020, 13:50

assigned to @RensvdLinden

**Comment by Brend-Smits** [comment]
In GitLab by @RensvdLinden on Mar 18, 2020, 13:51

unassigned @RensvdLinden

**Comment by Brend-Smits** [comment]
In GitLab by @RamonPeek on Mar 23, 2020, 11:20

assigned to @RamonPeek

**Comment by Brend-Smits** [comment]
In GitLab by @RamonPeek on Mar 23, 2020, 15:35

unassigned @RamonPeek

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 26, 2020, 11:04

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 27, 2020, 11:58

mentioned in merge request !11

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 19:32

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
