### ISSUE TITLE
Invalid project name

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-backend#386]
**Describe the bug**
Identity Server project in our solution has an outdated name. 

**To Reproduce**
1. Open the project and in the explorer you will be able to see all our projects.
2. Identity server is the only one-digit project, this should get converted to 2-digit (08 instead of 6)

**Expected behavior**
The digit should get changed from 6 to 08, because at this moment we have a 06-project and the 6-project. This is basically a duplicate digit. 08 has not been used yet, and it is reserved for identity server.

By changing the name, you have to make sure all the underlying files (docker, maybe certificates?) also get updated, otherwise the name won't get recognized anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/55654104/109469117-e4962080-7a6d-11eb-833f-0bc79971d8cd.png)

**Comment by niraymak** [comment]
Please note that we did rename the IdentityServer before and it broke on our staging environment. That's why we renamed it back to 6_IdentityServer.
