### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#39]
In GitLab by @Brend-Smits on Mar 9, 2020, 22:38

* Define Models
* Implement Models

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 22, 2020, 22:18

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 23, 2020, 16:03

mentioned in merge request !6

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 26, 2020, 17:18

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
