### ISSUE TITLE
Add support for styled readme in the wizard

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-backend#392]
**Is your feature request related to a problem? Please describe.**
Currently, the readme for each project is retrieved as a raw string. So the styling in the readme gets removed. This is not wanted of course.

**Describe the solution you'd like**
Research and implement a scalable way to retrieve a styled readme. 

**Additional context**
@waltersajtos is implementing the frontend implementation. Discuss together with him what a good way of implementing this could be.

**Comment by DamienKusters** [comment]
Is this feature specifically related to the wizard?
