### ISSUE TITLE
[Wiki] EF Migration 

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#393]
**Is your feature request related to a problem? Please describe.**
There still is no Wiki for managing Entity Framework migrations in Windows.

https://github.com/DigitalExcellence/dex-backend/wiki/Manage-migrations

**Describe the solution you'd like**
Add a clear explaination on how to manage migrations on the following wiki
https://github.com/DigitalExcellence/dex-backend/wiki/Manage-migrations

**Comment by TimSnoek123** [comment]
Added a small comment that its possible you can also use the Linux way to do migrations on Windows. I always use that way too.

**Comment by niraymak** [comment]
https://github.com/DigitalExcellence/dex-backend/wiki/Manage-migrations
