### ISSUE TITLE
Documentation message broker usage

### ISSUE THREAD

**Issue by Maxvanhattum** [DigitalExcellence/dex-backend#398]
**Is your feature request related to a problem? Please describe.**
At the moment we use RabbitMQ and a custom library to publish, distribute and listen to tasks/payloads. 
While there is a technical design: https://drive.google.com/file/d/10iH2Z80MzR3aLKWOcGFo6Hj8Es3szzJQ/view?usp=sharing ,
there is no easy to understand guide on how to use existing services or create new service that might need to utilize the message broker.

**Describe the solution you'd like**
A easy to understand guide needs to be written that fellow developers can follow or reference when wanting to create an application that needs to use the message broker. This guide needs to be published on the wiki.

**Comment by Maxvanhattum** [comment]
First draft:
https://drive.google.com/file/d/1_rwuHNyKnIOAFnvkNJE9MJoNZpW977vP/view?usp=sharing
Screenshots are from the feature/63-recommencationsystem branch, there might be some slight name differences in comparison to develop. However previous mentioned issue will probably be implemented soon.

**Comment by niraymak** [comment]
No remark for the technical design! Good work. I think this can be added to the Wiki.
Not sure if we should add a new Wiki page or add it to the SAD wiki (link below). 
https://github.com/DigitalExcellence/dex-backend/wiki/Software-Architecture-Document

Did not read the whole messagebroker guide yet but added some minor comments for the part I read.

**Comment by niraymak** [comment]
> No remark for the technical design! Good work. I think this can be added to the Wiki.
> Not sure if we should add a new Wiki page or add it to the SAD wiki (link below).
> https://github.com/DigitalExcellence/dex-backend/wiki/Software-Architecture-Document
> 
> Did not read the whole messagebroker guide yet but added some minor comments for the part I read.

@RubenFricke Where do you think the technical part should be uploaded on the Wiki?

**Comment by RubenFricke** [comment]
I think it would be best to split the C4 model per (large) functionality. This way you can add some explanation to each part to make individual parts more clear for our readers. Just a few lines can help a lot. 

If we would add everything in one page, I think it can get quite overwhelming at a certain point. This is not the case yet, but it might be something to consider.

**Comment by niraymak** [comment]
@Maxvanhattum reviewed your guide for the messagebroker.
Very extensive guide. Made some comments on a Google Doc copy since the original is a .pdf. 
I guess you should put this guide on Medium, haha 👍 

https://docs.google.com/document/d/1Utr_SOvn3zbgfJ6SboK9Dpy7jbW_CdXMAyPx0Ij1858/edit?usp=sharing

**Comment by niraymak** [comment]
@JVerbruggen status on review?
