### ISSUE TITLE
Migrate to new VPS servers

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#407]
**Is your feature request related to a problem? Please describe.**
We will switch from OVH VPS servers to YourHosting provided by FHICT.

**Describe the solution you'd like**
- Prepare YourHosting VPS servers to operate as our new staging and production servers.
- Switch DNS records to YourHosting IP's.
- Provide GitHub keys with new hosting variables.

**Production URL**

**Additional context**

**Comment by niraymak** [comment]
Staging VPS is succesfully migrated to YourHosting. Ruben and I are writing a document to make transfering to a new VPS more easily in the future. We will use this document to check migrate the production VPS to see if all commands are correct.

**Comment by RubenFricke** [comment]
Migration is finished. The created document about the migration can be found here: https://docs.google.com/document/d/1fumlkbXwI_ZHRYJIh_XQ-tQzvOcfzTL4KTJzHqqfiF4/edit#heading=h.aczyuw2yex2w
