### ISSUE TITLE
Refactor controllers

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#411]
**Is your feature request related to a problem? Please describe.**
In the retrospective one of the points of attention was that there is too much logic / code in the endpoints in the API.
An example is in the link below.

**Describe the solution you'd like**
Research and refactor a way to make endpoints shorter.

**Production URL**
https://github.com/DigitalExcellence/dex-backend/blob/develop/API/Controllers/ProjectController.cs#L384

**Comment by Arilith** [comment]
I spoke about this with Niray last Friday and will research a solution in the coming time. One thing that already definitely could help is a central exception/error class, which would move all the exceptions to their own respective place instead of in the controllers.

**Comment by Arilith** [comment]
The research document can be found at 
https://drive.google.com/file/d/13LsDxa7freZ_0pY4PnHCyUgI6jcYaSY7/view?usp=sharing

**Comment by MeesvanStraten** [comment]
@Arilith  Hey, Are you still working on DeX this semester? and maybe even on this issue? Thanks!

**Comment by Arilith** [comment]
> @Arilith  Hey, Are you still working on DeX this semester? and maybe even on this issue? Thanks!

Hi Mees,

No, sadly I won't be joining Dex this semester as I've moved to the TU/e and probably won't have time to work on this. I wish you all the best of luck this semester!
