### ISSUE TITLE
Multiple call to actions

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-backend#416]
**Is your feature request related to a problem? Please describe.**
When the project detail page's design was made, we decided it would make sense to have multiple call-to-action buttons. With the current implementation, this is not possible

**Describe the solution you'd like**
Add functionality to link multiple call-to-actions to 1 project.

**Comment by niraymak** [comment]
Waiting for frontend implementation. Good work! DigitalExcellence/dex-frontend#454
