### ISSUE TITLE
Swagger does not work in production environment

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#429]
**Describe the bug**
On both https://api.staging.dex.software/ and https://staging.dex.software/ the identityserver returns "Unauthorized client" after trying to authorize.

**To Reproduce**
1. Go to https://api.staging.dex.software/ 
2. Authorize
3. Identity returns: Unauthorized client

**Expected behavior**
Research and refactor so the Identity server is able to authorize Swagger.

**Screenshots**
![image](https://user-images.githubusercontent.com/44868678/115224574-505f4600-a10d-11eb-8ee1-8b17311c213f.png)

**Comment by TimSnoek123** [comment]
Dunno if this is still an issue, but its, from what ive seen, highly likely that one of the parameters doesn't conform with the url in the identity server. For example the return url.

**Comment by niraymak** [comment]
You were right @TimSnoek123 😄
