### ISSUE TITLE
Add image to highlighted projects

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-backend#431]
**Is your feature request related to a problem? Please describe.**
When highlighting a project, an image should be able to get added. On the front end, we will show highlighted projects with an 'inspiring' image. To keep control, we would like to add an image that will be shown when that highlighted project is focused.

**Describe the solution you'd like**
When highlighting a project, an image (file) should be added to the highlight.

**Additional context**
Homepage on frontend: https://github.com/DigitalExcellence/dex-frontend/issues/380

**Comment by niraymak** [comment]
Will be picked up tomorrow by Ruben and Fleur.
