### ISSUE TITLE
Api container not composing due to error

### ISSUE THREAD

**Issue by Zarthenix** [DigitalExcellence/dex-backend#432]
**Describe the bug**
After getting a clean install from the Development-branch, the API-container wouldn't boot in Docker due to an error:

  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The MERGE statement conflicted with the FOREIGN KEY constraint "FK_User_Institution_InstitutionId". The conflict occurred in database "master", table "dbo.Institution", column 'Id'.
api                    | The statement has been terminated.

**To Reproduce**
1. Pull Development-branch
2. Use docker-compose up
3. Check error log, container will not launch

**Expected behavior**
Docker-compose executed and containers started

**Screenshots**
![image](https://user-images.githubusercontent.com/44115393/115867953-0394ab80-a43c-11eb-91fa-8a8422dca306.png)

**Comment by niraymak** [comment]
Try docker-compose down -v.

**Comment by Zarthenix** [comment]
This has solved the issue, thanks!
