### ISSUE TITLE
Get All Projects performance

### ISSUE THREAD

**Issue by TimSnoek123** [DigitalExcellence/dex-backend#436]
The current GetAllWithUsersCollaboratorsAndInstitutionsAsync which gets the projects for the projects page is really inefficient the query gets data 2 times while include already gets the data in the first .ToListAsync(). Furthermore the ToListAsync() gets called twice for some reason?

![image](https://user-images.githubusercontent.com/45255534/117355363-c5bf6a80-aeb2-11eb-8af9-f0db6f9b8bea.png)

**Comment by TimSnoek123** [comment]
The Load() is also quite weird, so I think its pretty easy to quickly optimize this function a bit more

**Comment by TimSnoek123** [comment]
Put it sprint 11 for now, since I can't find sprint 12.

**Comment by niraymak** [comment]
Performance is better after merging this PR, however with "awesome dot net" it is for some reason on the servers slower. Local debugging is also faster with awesome dot which is weird.

We now will try to not retrieve the long description from the database.
