### ISSUE TITLE
Filter categories

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#444]
**Is your feature request related to a problem? Please describe.**
It should be possible to filter through categories.

**Describe the solution you'd like**
Implement a way to filter on categories. The endpoint should be able to return all projects with one or more categories depending on the ones selected.

If possible please reuse this endpoint: https://github.com/DigitalExcellence/dex-backend/blob/develop/API/Controllers/ProjectController.cs#L160

**Production URL**
https://dex.software/project/overview

**Additional context**

**Comment by waltersajtos** [comment]
![afbeelding](https://user-images.githubusercontent.com/32552097/119794569-ee49eb80-bed7-11eb-88ed-6337ea60bf40.png)
Also change the getAllCategories endpoint to public.

**Comment by waltersajtos** [comment]
Probably also a good idea to get the naming consistent for the Category recourses. 

```cs
public class ProjectCategoryResource
    {

        /// <summary>
        ///     Gets or sets the Id of the category.
        /// </summary>
        public int CategoryId { get; set; }
    }
```

```cs
public class ProjectCategoryResource
    {

        public class ProjectCategoryResourceResult
    {

        /// <summary>
        ///     Gets or sets the Id of the project category.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        ///     Gets or sets the Name of the project category.
        /// </summary>
        public string Name { get; set; }

    }
    }
```
