### ISSUE TITLE
Score projects

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#453]
**Is your feature request related to a problem? Please describe.**
Currently our frontend shows projects by default sorted [Updated (new - old)]. It would be nice to score our projects and sort projects on (activity) score.

**Describe the solution you'd like**
Research an algorithm to give our projects a score. For example on basis of project likes, latest update and viewers. This score can be calculated every week 

Maybe external data like GitHub stars could also be considered. But this should be fair against other non-Github projects or private Github projects.

**Production URL**

**Additional context**
For some more information about how this could work for us: https://patterns.innersourcecommons.org/p/repository-activity-score

**Comment by MeesvanStraten** [comment]
@BartvanEijkelenburg  Maybe you can use this issue when you are brainstorming next week. This issue comes really close to the one you are taking. #522
