### ISSUE TITLE
Add pagination to GetUserProjects endpoint

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-backend#461]
**Is your feature request related to a problem? Please describe.**
Add the pagination to the GetUserProjects endpoint in the UserController.

**Describe the solution you'd like**
Pagination should get added just like in the GetAllProjects endpoint on the ProjectController. However, keep DRY principles in your mind.

**Additional context**
Frontend implementation: https://github.com/DigitalExcellence/dex-frontend/issues/526

**Comment by waltersajtos** [comment]
I think it makes more sense to remove the get user projects and implement the functionality in the getProjects endpoint. I'm not sure if this is following the REST standard but it would prevent a lot of duplicate code.
