### ISSUE TITLE
Research: Database technology

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#47]
In GitLab by @StijnGroenen  on Mar 16, 2020, 13:21

Research the most appropriate database technology to use with Digital Excellence. This can be one single database or a combination of multiple different databases.

Examples:
*  SQL (MySQL, MSSQL, etc.)
*  NoSQL (Mongo, etc.)
*  GraphDB (Neo4J, etc.)

Do we need caching? (Redux, etc.)
  
Related Epic: https://git.fhict.nl/dex/dex-epics/-/issues/14

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 20:17

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 5, 2020, 21:16

assigned to @jcoenen96

**Comment by StijnGroenen** [comment]
This research is already on Google Drive.
Closing.
