### ISSUE TITLE
Wiki: How to setup local development

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#48]
In GitLab by @Brend-Smits on Mar 26, 2020, 11:06

* How do developers get started and set up for local development?
* Note that you should not only focus on Visual studio, but also keep it broad so people can use whatever IDE on whatever operating system they like.  
  
Related Epic: https://git.fhict.nl/dex/dex-epics/-/issues/14

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 20:19

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @RensvdLinden on Mar 30, 2020, 11:25

assigned to @RensvdLinden

**Comment by RensvdLinden** [comment]
https://github.com/DigitalExcellence/dex-backend/wiki/Getting-Started
