### ISSUE TITLE
Accounts before the change do not have all the rights to old projects 

### ISSUE THREAD

**Issue by DaveBouman** [DigitalExcellence/dex-backend#499]
**Describe the bug**
If an account was created before the roll changes the account does not have all the rights to the old projects. Still needs more research. Not a lot information.

**To Reproduce**
1. Get an account that was created before the account change.

**Expected behavior**

**Screenshots**

**Production URL**
Can this issue be linked to a relevant production URL? If so, please post the full link here, don't use hyperlinks.
If you can, post a short description around the url why it's relevant, this is good for SEO reasons.

**Additional context**

**Comment by DaveBouman** [comment]
Closes for the moment. Not reproducible

**Comment by patrickdb** [comment]
I still have the issue.

- Logged in under my FHICT account
- Surfed to older projects (https://dex.software/project/details/16-Refactor-Guidance-Tool)
- Only able to view the details, cannot add categories, make changes, or whatever
