### ISSUE TITLE
project endpoint search by multiple id's

### ISSUE THREAD

**Issue by MeesvanStraten** [DigitalExcellence/dex-backend#547]
**Is your feature request related to a problem? Please describe.**
The stakeholders requested an endpoint to fetch projects by multiple id's. This allows Plex to use DeX efficiently.
Currently only all projects or a single project can be fetched. 

**Describe the solution you'd like**
An endpoint that takes multiple project id's and returns the projects.

In the project controller an endpoint should be created that takes an array of id's and returns all projects matching these id's.
The project controllers calls the service layer which calls the data (repository layer) which get's the data from the database.
The entity that need's to be fetched is called "Project" and is located in the "Model" project of the solution.

**Comment by naomiceron** [comment]
Hello! I would like to give this issue a try, could you assign it to me? :)

**Comment by RubenFricke** [comment]
@MeesvanStraten , can you notify @naomiceron if she can pick this issue up?

**Comment by MeesvanStraten** [comment]
@naomiceron  Hey, Sorry for the late response. Sure I just assigned it to you.

**Comment by MeesvanStraten** [comment]
@naomiceron  I've updated the issue, if you need more information just contact me :).
