### ISSUE TITLE
Research: How can we tag and categorize projects?

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#58]
In GitLab by @Brend-Smits on Mar 29, 2020, 18:10

We need to research what are good ways to 'tag' and (automatically?) categorize projects.    
Definition of 'tag': *a label attached to someone or something for the purpose of identification or to give other information.*
Possible tags could be: C#, Java, Psychology, Math, Database
  
The second part of this research will be regarding categories, we need to know how we can best categorize projects so it's relevant for everyone. It needs to be relevant for IT students, but also for people from Psychology or Mechanical Engineering.  
* What tags and categories should we use?
* Should we automate this process?
* How can we automate this process? 

Tags and categories could be used to improve search/recommendation system  
Based on this research we should decide whether or not move forward with implementation for Tags and/or Categories  
  
Related Epic: https://git.fhict.nl/dex/dex-epics/-/issues/1

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 18:15

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 18:16

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Apr 17, 2020, 18:28

mentioned in merge request dex-frontend!19

**Comment by niraymak** [comment]
Please read the conclusion of this research before you start researching this issue:

https://docs.google.com/document/d/1B1u_j5jQXmv3GVPG-HrXYJLR8rVKbtAhEkLjbac6KSs/edit?usp=sharing

**Comment by JVerbruggen** [comment]
Tags are saved with their own controller and have a many-to-many relationship with projects.

- Who should be able to execute CRUD tasks on tags? Administrators?
- Who should be able to add existing tags to projects? All project collaborators?

Please review @niraymak

**Comment by niraymak** [comment]
> Tags are saved with their own controller and have a many-to-many relationship with projects.
> 
> * Who should be able to execute CRUD tasks on tags? Administrators?
> * Who should be able to add existing tags to projects? All project collaborators?
> 
> Please review @niraymak

I would say administrators are able to do CRUD tasks on tags. Owner of the project is able to edit tags linked to the project.
@Ruby77 What are your thoughts?

**Comment by Ruby77** [comment]
I agree with @niraymak . But don't forget the data officer. He should be able to edit tags on projects from users from the same institute.
