### ISSUE TITLE
Sort projects

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#59]
In GitLab by @Brend-Smits on Mar 29, 2020, 18:14

Users will want to be able to sort projects:
* Sort on Date (asc or desc) 
* Name of project (asc or desc)
* Other ways to sort?
  
Ensure to discuss with other project members to see how to implement this. Should be very similar to #55   
Related Epic: https://git.fhict.nl/dex/dex-epics/-/issues/1

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 18:14

changed the description

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Apr 8, 2020, 16:35

@jcoenen96 would you like to take on this issue? Since you already implemented pagination and had ideas on how to tackle this on the backend?

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 14, 2020, 10:33

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 16, 2020, 17:13

created merge request !20 to address this issue

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 16, 2020, 17:13

mentioned in merge request !20

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 16, 2020, 17:16

mentioned in merge request !21

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Apr 19, 2020, 20:27

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
