### ISSUE TITLE
Editor config file

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#69]
In GitLab by @Brend-Smits on Mar 30, 2020, 14:09

Based of the coding guidelines discussed in #50 we should create an editor configuration file and put it in the git repo so that we can use it in the pipeline and so that IDE's automatically detect it and use it
  
Related Epic: https://git.fhict.nl/dex/dex-epics/-/issues/14

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 5, 2020, 21:15

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 6, 2020, 17:12

mentioned in merge request !17

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Apr 18, 2020, 18:54

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
