### ISSUE TITLE
Wiki: Coding guidelines

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#72]
In GitLab by @Brend-Smits on Apr 1, 2020, 15:52

Now that we have defined the coding guidelines, we should make a wiki article out of it.

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 5, 2020, 21:14

https://git.fhict.nl/dex/dex-backend/-/wikis/Guides/Coding-guidelines

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 5, 2020, 21:14

assigned to @jcoenen96

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Apr 19, 2020, 11:06

closed

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
