### ISSUE TITLE
Feature/37 Create Models - [merged]

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#86]
In GitLab by @jcoenen96 on Mar 23, 2020, 16:03

_Merges feature/37_Create_Models -> develop_

Merge request for issue #37.
Updated the models and resource schemas to follow the specifications.

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 23, 2020, 17:12

added 1 commit

<ul><li>8c8cb532 - Added short description to project model</li></ul>

[Compare with previous version](/dex/dex-backend/-/merge_requests/6/diffs?diff_id=19238&start_sha=b2c4871a06676a6ae65efea13134e70de614b9a4)

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Mar 24, 2020, 10:29

```suggestion:-0+0
        public string[] Contributors { get; set; }

        public Date CreatedDate { get; set; }
```

**Comment by Brend-Smits** [comment]
In GitLab by @wotwot on Mar 25, 2020, 16:52

Should we also add a updatedat field?

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 25, 2020, 16:52

added 1 commit

<ul><li>c025cd2d - Added created and updated properties to project model</li></ul>

[Compare with previous version](/dex/dex-backend/-/merge_requests/6/diffs?diff_id=19399&start_sha=8c8cb5322cf0f97bca058c102e86c8fc54e656a2)

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 25, 2020, 16:55

I added both the created en the updated properties.

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Mar 25, 2020, 16:55

resolved all threads

**Comment by Brend-Smits** [comment]
In GitLab by @wotwot on Mar 25, 2020, 17:17

enabled an automatic merge when the pipeline for c025cd2dc7ae0b5649ce9addce4986de1c1186e2 succeeds

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 26, 2020, 10:51

canceled the automatic merge

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 26, 2020, 10:51

mentioned in commit 4c86ec3d9f725e5fe6b742cfbdbe2e4d37ce0abf

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 26, 2020, 10:51

merged

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
