### ISSUE TITLE
Cleanup - [merged]

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#89]
In GitLab by @StijnGroenen on Mar 27, 2020, 17:30

_Merges cleanup -> develop_

Disabled authorization for the demo
Use resources on api result
added design package to api
moved bogus to data
moved seeding to data
return user with projects

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Mar 29, 2020, 15:32

added 15 commits

<ul><li>c6a39f70...96ff1bad - 13 commits from branch <code>develop</code></li><li>116ff74e - Merge branch &#39;develop&#39; into cleanup</li><li>b1839a4b - Merge branch &#39;develop&#39; into cleanup</li></ul>

[Compare with previous version](/dex/dex-backend/-/merge_requests/13/diffs?diff_id=19717&start_sha=c6a39f70bab571589661da31930076f27340cd63)

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Mar 29, 2020, 18:19

added 1 commit

<ul><li>1c74edf2 - Return user and collaborator with a single project and return notFound instead of noContent</li></ul>

[Compare with previous version](/dex/dex-backend/-/merge_requests/13/diffs?diff_id=19718&start_sha=b1839a4bd90d2c4f15020fd722f8a4af8a000248)

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Mar 29, 2020, 19:10

added 2 commits

<ul><li>c7ce4198 - </li><li>761eac10 - </li></ul>

[Compare with previous version](/dex/dex-backend/-/merge_requests/13/diffs?diff_id=19722&start_sha=1c74edf2d45ee0a09957f0bf5380931ac99c48b4)

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 19:19

merged

**Comment by Brend-Smits** [comment]
In GitLab by @Brend-Smits on Mar 29, 2020, 19:19

mentioned in commit 2da5d398b73383c835703cff2b65c8119fcd7031

**Comment by StijnGroenen** [comment]
Switched the assigned user to @jcoenen96 because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
