### ISSUE TITLE
Deleted secrets and connection string - [merged]

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#91]
In GitLab by @RensvdLinden on Apr 11, 2020, 14:58

_Merges feature/remove_secrets -> develop_

Deleted the secrets and the connection string so we can set them with environment variables when we migrate.

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Apr 11, 2020, 15:03

merged

**Comment by Brend-Smits** [comment]
In GitLab by @StijnGroenen on Apr 11, 2020, 15:03

mentioned in commit 5b5c2c00e785a7cf6616d40ae928f66eaad87e82

**Comment by StijnGroenen** [comment]
Switched the assigned user to @jcoenen96 because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
