### ISSUE TITLE
Feature/79 refactor cleanup - [merged]

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#95]
In GitLab by @Brend-Smits on Apr 19, 2020, 18:27

_Merges feature/79-refactor-cleanup -> develop_

General cleanup, refactored some stuff and put some comments

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 19, 2020, 18:30

merged

**Comment by Brend-Smits** [comment]
In GitLab by @jcoenen96 on Apr 19, 2020, 18:30

mentioned in commit abda91cf065c7e970b8e46a555ecd87ca140b216

**Comment by StijnGroenen** [comment]
Switched the assigned user to me because @jcoenen96 and @StijnGroenen were switched during the migration from GitLab to GitHub due to an incorrect mapping.
